conditional-nametags:
  enabled: false
  show-by-default: true
conditional-appearance:
  enabled: false
  show-by-default: true


actionbars:
  enabled: false
  /toggleactionbar: true
  bars:
    staff:
      condition: "permission:tab.staff"
      text: "&aEpic &bActionbar &cfor &depic &epeople&f!"
    welcome:
      text: "&2Welcome &a%player%&2!"

titles:
  enabled: false
  /toggletitle: true
  titles:
    welcome:
      title: "&2Welcome &a%player%&2,"
      subtitle: "&2on &aplay.servername.com&2!"

unlimited-nametags:
  enabled: true
  toggle-command: /nametags
  rotation: true
  lines:
    admin:
      display-condition: "permission:tab.admin"
      type: block
      block: diamond_block
    staff:
      display-condition: "permission:tab.staff;!permission:tab.admin"
      type: item
      material: diamond
    name:
      type: text
      text: "%tab_tagprefix%%tab_customtagname%%tab_tagsuffix%"